import datetime
from sqlalchemy.orm import Session
from app.core.logging import logger
from app.db.models.cattle import Cattle
from app.db.models.alert import Alert
from app.db.models.prediction import HealthPrediction
from app.db.models.veterinary import VeterinaryAppointment

def trigger_automated_health_workflow(
    db: Session,
    cattle: Cattle,
    health_status: str,
    risk_score: float,
    reason: str,
    confidence: float
) -> dict:
    """
    CATTLEX Automated Health Workflow:
    Executes event-driven state transitions, persistent logging, triage alert dispatch,
    and automatic veterinary appointment generation when cattle becomes AT_RISK or CRITICAL.
    """
    previous_status = cattle.status
    cattle.status = health_status
    cattle.updated_at = datetime.datetime.utcnow()

    actions_taken = []

    # 1. Persist Health Prediction
    prediction = HealthPrediction(
        cattle_id=cattle.id,
        health_status=health_status,
        risk_score=risk_score,
        model_name="VitalRiskEngine-v1",
        confidence=confidence,
        prediction_reason=reason
    )
    db.add(prediction)
    actions_taken.append("Recorded health prediction and risk score")

    # 2. Trigger Alert if state is not HEALTHY
    if health_status in ["AT_RISK", "CRITICAL"]:
        severity = "CRITICAL" if health_status == "CRITICAL" else "WARNING"
        alert_msg = (
            f"Automated Triage: {cattle.tag_id} ({cattle.name}) transitioned to {health_status} "
            f"(Risk Score: {risk_score}/100). Physiological alerts: {reason}. "
            f"Veterinary evaluation recommended."
        )
        
        # Check if an identical active alert already exists recently to avoid spam
        existing_alert = db.query(Alert).filter(
            Alert.cattle_id == cattle.id,
            Alert.status == "ACTIVE",
            Alert.severity == severity
        ).first()

        if not existing_alert:
            new_alert = Alert(
                cattle_id=cattle.id,
                type="MULTI_VITAL",
                severity=severity,
                message=alert_msg,
                status="ACTIVE"
            )
            db.add(new_alert)
            actions_taken.append(f"Dispatched {severity} alert to farmer dashboard")

        # 3. Automated Veterinary Appointment Triage
        priority = "URGENT" if health_status == "CRITICAL" else "HIGH"
        existing_apt = db.query(VeterinaryAppointment).filter(
            VeterinaryAppointment.cattle_id == cattle.id,
            VeterinaryAppointment.status.in_(["PENDING", "SCHEDULED"])
        ).first()

        if not existing_apt:
            scheduled_time = datetime.datetime.utcnow() + (datetime.timedelta(hours=2) if health_status == "CRITICAL" else datetime.timedelta(hours=12))
            appointment = VeterinaryAppointment(
                cattle_id=cattle.id,
                veterinarian_name="Dr. Sarah Jenkins, DVM",
                reason=f"Automated RPA Trigger: {health_status} state detected. Risk score {risk_score}. {reason}",
                priority=priority,
                scheduled_at=scheduled_time,
                status="PENDING",
                notes=f"Auto-generated by CATTLEX Workflow Automation on {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}."
            )
            db.add(appointment)
            actions_taken.append(f"Created automated {priority} veterinary consultation appointment")

    db.commit()
    db.refresh(cattle)

    logger.info(f"CATTLEX Workflow executed for {cattle.tag_id}: {health_status} -> Actions: {actions_taken}")
    return {
        "tag_id": cattle.tag_id,
        "previous_status": previous_status,
        "new_status": health_status,
        "risk_score": risk_score,
        "actions_taken": actions_taken
    }
